MODEL:
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [57.375, 57.120, 58.395]
  WEIGHTS: "./pvt_v2_b2_li_C4.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE_AT: 1
    NAME: "build_PVT_backbone"
    TYPE: "pvt_v2_b2_li"
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "PVTROIHeads"
DATASETS:
  TRAIN: ("voc_2007_trainval_base3", "voc_2012_trainval_base3")
  TEST: ("voc_2007_test_all3",)
  TEST_KEEPCLASSES: 'all3'
  TEST_SHOTS: (1,2,3,5,10)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0002
  CHECKPOINT_PERIOD: 18000
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  WARMUP_ITERS: 100
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
OUTPUT_DIR: "./output/fsod/single_branch_pretraining_pascalvoc_split3_pvt_v2_b2_li/"
TEST:
  EVAL_PERIOD: 18000
VERSION: 2
